# -*- coding: utf-8 -*-
"""School_360.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xNQoL6na9QBcmAQnPjVjYEoNur45zu0R
"""

import sys
!{sys.executable} -m pip install streamlit
import streamlit as st
import matplotlib.pyplot as plt

st.set_page_config(page_title="School_360_App")

from datetime import date

student_id = st.text_input(
    "Student ID"
)

teacher_id = st.text_input(
    "Teacher ID"
)

assessment_date = st.date_input(
    "Assessment Date",
    value=date.today()
)

st.session_state["student_id"] = student_id
st.session_state["teacher_id"] = teacher_id
st.session_state["assessment_date"] = assessment_date

"""FUNCTIONS"""

def calculate_score(responses):
    total = 0

    for value in responses.values():   # LOOP
        total += value

    return total

def classify_risk(score):

    if score <= 11:
        return "Low Risk"  # Changed from "Normal or Low Risk" for consistency

    elif score <= 15:
        return "Medium Risk"
    else:
        return "High Risk, Further evaluation needed"

"""DICTIONARY AND LIST"""

questions = [
    "Often complains of headaches, stomach-aches or sickness",
    "Many worries, often seems worried",
    "Often unhappy, down-hearted or tearful",
    "Nervous or clingy in new situations, easily loses confidence",
    "Many fears or easily scared",
    "Often has temper tantrums or hot tempers",
    "Often fights with other children or bullies them",
    "Often lies or cheats",
    "Steals from home, school or elsewhere",
    "Restless or over-active",
    "Constantly fidgeting or squirming",
    "Easily distracted or concentration wanders",
    "Rather solitary, tends to play alone",
    "Picked on or bullied by other children",
    "Gets on better with adults than with other children",
    "Generally obedient, usually does what adults request",
    "Thinks things out before acting",
    "Sees tasks through to the end, good attention span",
    "Has at least one good friend",
    "Generally liked by other children"
]

print(len(questions))

reverse_questions = [
    "Generally obedient, usually does what adults request",
    "Thinks things out before acting",
    "Sees tasks through to the end, good attention span",
    "Has at least one good friend",
    "Generally liked by other children"
]

print(len(reverse_questions))

options = {
    "Not true": 0,
    "Somewhat true": 1,
    "Certainly true": 2
}

"""SCORING LOGIC"""

scores = {}
st.subheader("SDQ_T_Questionnaire")

for q in questions:
    ans = st.radio(q, list(options.keys()), key=q)
    raw = options[ans]

    if q in reverse_questions:
        score = 2 - raw
    else:
        score = raw

    scores[q] = score

total_score = sum(scores.values())

"""RESULTS AND RECOMMENDATIONS"""

if st.button("Calculate Result"):
    st.subheader("SDQ_T_Results")
    score = calculate_score(scores)

    category = classify_risk(score)

    st.success(f"Total Score: {score}")
    st.info(f"Risk Category: {category}")


    st.subheader("Mental_Health_Screening_Recommendation")

    if category == "Low Risk":
        recommendation = "Continue healthy habits, scheduled longitudinal monitoring recommended."

    elif category == "Medium Risk":
        recommendation = "Monitor emotional wellbeing and seek support if needed."

    else:
        recommendation = "Professional counselling referral is recommended."

    st.write(recommendation)

    st.session_state["sdq_total"] = score
    st.session_state["sdq_category"] = category
    st.session_state["sdq_recommendation"] = recommendation
    st.session_state["sdq_completed"] = True

"""SDQ_DOMAINS_DICTIONARY_BETTER_SUBSCALE_VISUALIZATION"""

sdq_domains = {
    "Emotional": [
        "Often complains of headaches, stomach-aches or sickness",
        "Many worries, often seems worried",
        "Often unhappy, down-hearted or tearful",
        "Nervous or clingy in new situations, easily loses confidence",
        "Many fears or easily scared"
    ],

    "Behavioural": [
        "Often has temper tantrums or hot tempers",
        "Often fights with other children or bullies them",
        "Often lies or cheats",
        "Steals from home, school or elsewhere"
    ],

    "Hyperactivity": [
        "Restless or over-active",
        "Constantly fidgeting or squirming",
        "Easily distracted or concentration wanders"
    ],

    "Peer": [
        "Rather solitary, tends to play alone",
        "Picked on or bullied by other children",
        "Gets on better with adults than with other children"
    ],

    "Prosocial": [
        "Generally obedient, usually does what adults request",
        "Thinks things out before acting",
        "Sees tasks through to the end, good attention span",
        "Has at least one good friend",
        "Generally liked by other children"
    ]
}
emotional = sum(scores[q] for q in sdq_domains["Emotional"])
behavioural = sum(scores[q] for q in sdq_domains["Behavioural"])
hyperactivity = sum(scores[q] for q in sdq_domains["Hyperactivity"])
peer = sum(scores[q] for q in sdq_domains["Peer"])
prosocial = sum(scores[q] for q in sdq_domains["Prosocial"])

domain_scores = {
    "Emotional": emotional,
    "Behavioural": behavioural,
    "Hyperactivity": hyperactivity,
    "Peer": peer,
    "Prosocial": prosocial
}

"""VISUALIZATION USING MATPLOTLIB"""

import matplotlib.pyplot as plt

domains = list(domain_scores.keys())
scores = list(domain_scores.values())

fig, ax = plt.subplots(figsize=(8, 4))

ax.bar(domains, scores)

ax.set_title("SDQ Subscale Scores")
ax.set_ylabel("Score")
ax.set_ylim(0, 10)

for i, score in enumerate(scores):
    ax.text(i, score + 0.2, str(score), ha="center")

plt.tight_layout()

st.pyplot(fig)

"""PHYSICAL HEALTH SCREENING

BMI_ASSESSMENT
"""

import pandas as pd
boys_ref=pd.read_csv("boys_ref.csv")
girls_ref=pd.read_csv("girls_ref.csv")

"""BMI_FUNCTION"""

st.subheader("BMI Assessment")

age = st.number_input(
    "Age (Years)",
    min_value=5,
    max_value=19,
    step=1
)

gender = st.selectbox(
    "Gender",
    ["Male", "Female"]
)

height_cm = st.number_input(
    "Height (cm)",
    min_value=50.0,
    max_value=250.0,
    step=0.1
)

weight_kg = st.number_input(
    "Weight (kg)",
    min_value=1.0,
    max_value=200.0,
    step=0.1
)

"""BMI_CATEGORY"""

def bmi_category(age, gender, bmi):

    age_months = age * 12

    if gender == "Male":
        ref = boys_ref
    else:
        ref = girls_ref

    row = ref.iloc[
        (ref["Month"] - age_months).abs().argsort()[:1]
    ]

    sd2neg = float(row["SD2neg"].iloc[0])
    sd1 = float(row["SD1"].iloc[0])
    sd2 = float(row["SD2"].iloc[0])

    if bmi < sd2neg:
        return "Underweight"

    elif bmi <= sd1:
        return "Normal"

    elif bmi <= sd2:
        return "Overweight"

    else:
        return "Obese"

"""BMI_RESULT_AND_RECOMMENDATION"""

def calculate_bmi(weight_kg, height_cm):
    return weight_kg / ((height_cm / 100) ** 2)


if st.button("Calculate BMI"):

    bmi = calculate_bmi(
        weight_kg,
        height_cm
    )

    category = bmi_category(
        age,
        gender,
        bmi
    )

    st.success(f"BMI = {bmi:.2f}")

    st.info(f"Category = {category}")

    st.subheader("BMI Recommendation")

    if category == "Normal":
        recommendation = (
            "Healthy growth pattern observed. "
            "Continue balanced nutrition, regular physical activity, "
            "and routine health monitoring."
        )

    elif category == "Underweight":
        recommendation = (
            "Nutritional assessment recommended. "
            "Review dietary intake and monitor growth pattern. "
            "Consider referral for medical evaluation if concerns persist."
        )

    elif category == "Overweight":
        recommendation = (
            "Lifestyle and dietary counselling recommended. "
            "Encourage healthy eating habits, increased physical activity, "
            "and periodic weight monitoring."
        )

    else:
        recommendation = (
            "Medical evaluation and weight management counselling recommended. "
            "Comprehensive assessment and follow-up are advised."
        )

    st.write(recommendation)

    # Save results for summary report
    st.session_state["bmi_value"] = round(bmi, 1)
    st.session_state["bmi_result"] = category
    st.session_state["bmi_recommendation"] = recommendation
    st.session_state["bmi_completed"] = True

"""BLOOD_PRESSURE_ASSESSMENT"""

st.subheader("Blood Pressure Assessment")

sbp = st.number_input(
    "Systolic Blood Pressure (mmHg)",
    min_value=50,
    max_value=250,
    step=1
)

dbp = st.number_input(
    "Diastolic Blood Pressure (mmHg)",
    min_value=30,
    max_value=150,
    step=1
)

"""BP_REFERENCE_DICTIONARIES"""

bp_boys = {

    5: {"SBP": 106, "DBP": 63},
    6: {"SBP": 107, "DBP": 68},
    7: {"SBP": 109, "DBP": 70},
    8: {"SBP": 110, "DBP": 71},
    9: {"SBP": 110, "DBP": 73},
    10: {"SBP": 112, "DBP": 74},
    11: {"SBP": 114, "DBP": 75},
    12: {"SBP": 117, "DBP": 75}

}

bp_girls = {

    5: {"SBP": 107, "DBP": 64},
    6: {"SBP": 108, "DBP": 68},
    7: {"SBP": 109, "DBP": 70},
    8: {"SBP": 110, "DBP": 71},
    9: {"SBP": 111, "DBP": 72},
    10: {"SBP": 112, "DBP": 73},
    11: {"SBP": 114, "DBP": 74},
    12: {"SBP": 116, "DBP": 75}

}

"""BP_FUNCTION"""

def bp_screening(age, gender, sbp, dbp):

    if age >= 13:

        if sbp < 120 and dbp < 80:
            return "Normal"

        return "Abnormal"

    if gender == "Male":

        cutoff_sbp = bp_boys[age]["SBP"]
        cutoff_dbp = bp_boys[age]["DBP"]

    else:

        cutoff_sbp = bp_girls[age]["SBP"]
        cutoff_dbp = bp_girls[age]["DBP"]

    if sbp >= cutoff_sbp or dbp >= cutoff_dbp:

        return "Abnormal"

    return "Normal"

"""BLOOD_PRESSURE_RESULT_AND_RECOMMENDATION"""

if st.button("Assess Blood Pressure"):

    bp_result = bp_screening(
        age,
        gender,
        sbp,
        dbp
    )

    st.subheader("Blood Pressure Screening Result")

    st.write(f"Systolic BP: {sbp} mmHg")

    st.write(f"Diastolic BP: {dbp} mmHg")

    st.write(f"Status: {bp_result}")




    st.subheader("BP_Recommendation")

    if bp_result == "Normal":

        recommendation_text = (
            "Blood pressure is within age-specific screening limits. Continue routine monitoring during school health assessments."
        )
        st.success(recommendation_text)

    else:

        recommendation_text = (
            "Blood pressure exceeds age-specific screening thresholds. Repeat BP measurement and seek pediatric assessment if elevated on repeat measurement."
        )
        st.warning(recommendation_text)
    st.session_state["bp_result"] = bp_result
    st.session_state["bp_recommendation"] = recommendation_text
    st.session_state["bp_completed"] = True

"""VISION_ASSESSMENT

VISUAL_ACQUITY
"""

st.subheader("Visual_Acuity_Screening")

st.info("""
Instructions for Teacher:

• Place the Snellen chart at 6 meters (20 feet) from the student.
• Ensure adequate lighting.
• Test one eye at a time.
• Cover the opposite eye without applying pressure.
• Record the smallest line read correctly for each eye.
""")




#Inputs

vision_options = [
    "6/6",
    "6/9",
    "6/12",
    "6/18",
    "6/24",
    "6/36",
    "6/60"
]

right_eye = st.selectbox(
    "Right Eye Visual Acuity",
    vision_options
)

left_eye = st.selectbox(
    "Left Eye Visual Acuity",
    vision_options
)

"""VISUAL_ACQUITY_RESULT_AND_RECOMMENDATION"""

if st.button("Assess Visual Acuity"):

    if right_eye in ["6/6", "6/9"] and left_eye in ["6/6", "6/9"]:

        result = "Normal Vision"

        recommendation = """
Visual acuity is within normal screening limits.

Continue routine vision screening.
"""

        st.success(result)
        st.info(recommendation)
        st.session_state["vision_result"] = result

    else:

        result = "Vision Referral Recommended"
        recommendation = """
Visual acuity is outside normal screening limits.

Referral to an ophthalmologist or optometrist is recommended for further evaluation.
"""
        st.warning(result)
        st.subheader("Vision Recommendation")
        st.write(recommendation)


        st.session_state["vision_result"] = result
        st.session_state["vision_recommendation"] = recommendation
        st.session_state["right_eye"] = right_eye
        st.session_state["left_eye"] = left_eye
        st.session_state["vision_completed"] = True

"""COLOR_VISION_ASSESSMENT


"""

from PIL import Image
import streamlit as st

image_path = "ishihara.ppm.png"

st.image(
    image_path,
    caption="Ishihara Color Vision Test"
)

img = Image.open(image_path)

st.subheader("Color Vision Screening")

st.info("""
Instructions:

• Ask the student to identify the number shown in each plate.
• For the final plate, ask whether a continuous curved line/path is visible.
• Record the student's responses.
""")

st.image(
    "/content/ishihara.ppm", # Corrected filename based on previous upload output
    width=600
)




plate1 = st.text_input("Plate 1 (Expected: 57)")
plate2 = st.text_input("Plate 2 (Expected: 8)")
plate3 = st.text_input("Plate 3 (Expected: 5)")
plate4 = st.text_input("Plate 4 (Expected: 26)")

plate5 = st.selectbox(
    "Plate 5 (Curved Line Visible?)",
    ["Yes", "No"]
)





if st.button("Assess Color Vision"):

    score = 0

    if plate1.strip() == "57":
        score += 1

    if plate2.strip() == "8":
        score += 1

    if plate3.strip() == "5":
        score += 1

    if plate4.strip() == "26":
        score += 1

    if plate5 == "Yes":
        score += 1




    st.write(f"Score: {score}/5")

    if score >= 4:

        result = "Adequate Color Vision"

        recommendation = """
Color vision screening passed.

No concerns identified.
"""
        st.success(result)
        st.write(recommendation)
        st.session_state["color_vision_completed"] = True

    else:

        result = "Further Assessment Recommended"

        recommendation = """
Possible color vision deficiency detected.

Referral for formal ophthalmologic assessment is recommended.
"""
    st.warning(result)
    st.write(recommendation)
    st.session_state["color_vision_completed"] = True

    st.session_state["color_vision_result"] = result
    st.session_state["color_vision_recommendation"] = recommendation

"""HAIR_HYGIENE_ASSESSMENT"""

st.subheader("Hair Hygiene Assessment")

hair_status = st.selectbox(
    "Select Hair Condition",
    [
        "Normal",
        "Dandruff Present",
        "Nits/Lice Present",
        "Scalp Lesion/Wound Present"
    ]
)

"""HAIR_HYGIENE_RESULT_AND_RECOMMENDATION"""

if st.button("Assess Hair Hygiene"):

    if hair_status == "Normal":

        result = "Healthy Hair and Scalp"

        recommendation = """
Hair and scalp appear healthy.

Continue routine hygiene practices.
"""

        st.success(result)
        st.write(recommendation)

    elif hair_status == "Dandruff Present":

        result = "Hair Hygiene Concern"

        recommendation = """
Dandruff observed.

Improve scalp hygiene and monitor symptoms.
"""

        st.warning(result)
        st.write(recommendation)

    elif hair_status == "Nits/Lice Present":

        result = "Hair Hygiene Concern"

        recommendation = """
Nits/lice observed.

Regular wet combing. Over-the-counter anti-lice shampoo advised.
"""

        st.warning(result)
        st.write(recommendation)

    else:

        result = "Referral Recommended"

        recommendation = """
Abnormal finding detected.

Further clinical assessment is recommended.
"""

        st.warning(result)
        st.write(recommendation)

    # Store results regardless of outcome
    st.session_state["hair_result"] = result
    st.session_state["hair_recommendation"] = recommendation
    st.session_state["hair_completed"] = True
    st.session_state["hair_status"] = hair_status

"""ORAL_HEALTH_ASSESSMENT"""

st.subheader("Oral Health Assessment")

teeth_status = st.selectbox(
    "Teeth Condition",
    [
        "Teeth Clean/White/Intact",
        "Dental Caries Present",
        "Missing/Yellow Teeth/Broken Tooth/Bad Breath"
    ]
)

oral_hygiene = st.selectbox(
    "Oral Hygiene",
    [
        "Good",
        "Fair",
        "Poor"
    ]
)

gum_status = st.selectbox(
    "Gum Condition",
    [
        "Healthy",
        "Swollen/Bleeding Gums"
    ]
)

if st.button("Assess Oral Health"):

    referral = False

    if teeth_status != "Teeth Clean/White/Intact":
        referral = True

    if gum_status != "Healthy":
        referral = True

    if oral_hygiene == "Poor":
        referral = True

    if referral:

        result = "Referral Recommended"

        recommendation = """
Oral health concern detected.

Dental assessment is recommended.
"""

        st.warning(result)
        st.write(recommendation)

    else:

        result = "Good Oral Health"

        recommendation = """
No significant oral health concerns identified.

Continue routine oral hygiene practices.
"""

        st.success(result)
        st.write(recommendation)

    # UI section (optional consistency)
    st.subheader("Oral Health Recommendation")
    st.write(recommendation)

    # IMPORTANT: store everything for report
    st.session_state["oral_result"] = result
    st.session_state["oral_recommendation"] = recommendation
    st.session_state["oral_completed"] = True

    # optional but useful for audit/report traceability
    st.session_state["teeth_status"] = teeth_status
    st.session_state["gum_status"] = gum_status
    st.session_state["oral_hygiene"] = oral_hygiene

"""SKIN_ASSESSMENT

"""

st.subheader("Skin Health Assessment")

skin_status = st.selectbox(
    "Skin Condition",
    [
        "Healthy Skin",
        "Rash Present",
        "Redness Present",
        "Dryness Present"
        "Watery/Bloody Skin Discharge Present",
        "Wound/Ulcer/Blisters Present",
        "Pale/Yellowish in general apperance"]

)

if st.button("Assess Skin Health"):

    if skin_status == "Healthy Skin":

        result = "Healthy Skin"

        recommendation = """
No visible skin abnormalities detected.
"""

        st.success(result)
        st.write(recommendation)


    else:

        result = "Referral Recommended"

        recommendation = """
Unclassified or significant abnormal skin finding.

Further clinical assessment is recommended.
"""

        st.warning(result)
        st.write(recommendation)

    st.subheader("Skin Recommendation")
    st.write(recommendation)

    st.session_state["skin_result"] = result
    st.session_state["skin_recommendation"] = recommendation
    st.session_state["skin_completed"] = True
    st.session_state["skin_status"] = skin_status

"""NAIL_HEALTH_ASSESSMENT"""

st.subheader("Nail Health Assessment")

nail_status = st.selectbox(
    "Nail Condition",
    [
        "Normal Nails",
        "Poor Nail Hygiene",
        "Brittle Nails",
        "Nail Pitting Present",
        "White Lines/Spots Present",
        "Red/Dark Lines Present"
    ]
)

if st.button("Assess Nail Health"):

    abnormal_nails = [
        "Brittle Nails",
        "Nail Pitting Present",
        "White Lines/Spots Present",
        "Red/Dark Lines Present"
    ]

    if nail_status == "Normal Nails":

        result = "Healthy Nails"

        recommendation = """
Nails appear healthy.

Continue routine personal hygiene practices.
"""

        st.success(result)
        st.write(recommendation)

    elif nail_status == "Poor Nail Hygiene":

        result = "Nail Hygiene Concern"

        recommendation = """
Poor nail hygiene observed.

Regular nail cleaning and trimming are recommended.
"""

        st.warning(result)
        st.write(recommendation)

    elif nail_status in abnormal_nails:

        result = "Nail Health Concern"

        recommendation = """
Abnormal nail findings detected.

Further clinical assessment is recommended.
"""

        st.warning(result)
        st.write(recommendation)

    else:

        result = "Referral Recommended"

        recommendation = """
Unclassified or significant nail abnormality detected.

Further clinical assessment is recommended.
"""

        st.warning(result)
        st.write(recommendation)

    # consistent UI section
    st.subheader("Nail Recommendation")
    st.write(recommendation)

    # session storage (safe placement)
    st.session_state["nail_result"] = result
    st.session_state["nail_recommendation"] = recommendation
    st.session_state["nail_completed"] = True
    st.session_state["nail_status"] = nail_status

"""GROSS_SUMMARY_CARD

SIMPLIFIED_DIGITAL_HEALTH_REPORT_FOR_BETTER_VISUALIZATION
"""

st.header("Overall Health Status")

def traffic_light(result):

    if result is None:
        return "⚪"

    result = str(result).lower()

    green_words = [
        "Normal",
        "Healthy",
        "Pass",
        "Low Risk",
        "Normal Vision",
        "Adequate Color Vision",
        "Healthy Hair and Scalp",
        "Good Oral Health",
        "Healthy Skin",
        "Healthy Nails"
    ]

    yellow_words = [
        "Borderline",
        "Medium Risk",
        "Hair Hygiene Concern",
        "Nail Hygiene Concern",
        "Mild",
        "Overweight",
        "Monitor",
        "Fair",

      ]

    red_words = [
        "Abnormal",
        "High Risk",
        "Underweight",
        "Obese",
        "Under Weight",
        "Vision Referal Recommended",
        "Further Assessment Recommended",
        "Referal Recommended",
        "Skin Health Concern",
        "Nail Health Concern",
        'Poor',
        "Oral Health Concern"
        ]

    if any(word in result for word in green_words):
        return "🟢"

    elif any(word in result for word in yellow_words):
        return "🟡"

    elif any(word in result for word in red_words):
        return "🔴"

    else:
        return "⚪"


dashboard = {

    "BMI":
        traffic_light(
            st.session_state.get("bmi_result")
        ),

    "Blood Pressure":
        traffic_light(
            st.session_state.get("bp_result")
        ),

    "Vision":
        traffic_light(
            st.session_state.get("vision_result")
        ),

    "Color Vision":
        traffic_light(
            st.session_state.get("color_vision_result")
        ),

    "Hair":
        traffic_light(
            st.session_state.get("hair_result")
        ),

    "Oral":
        traffic_light(
            st.session_state.get("oral_result")
        ),

    "Skin":
        traffic_light(
            st.session_state.get("skin_result")
        ),

    "Nails":
        traffic_light(
            st.session_state.get("nail_result")
        ),

    "SDQ":
        traffic_light(
            st.session_state.get("sdq_category")
        )
}

for module, status in dashboard.items():

    st.write(
        f"{status}  {module}"
    )

traffic_light_text = []

for module, status in dashboard.items():

    traffic_light_text.append(
        f"{status} {module}"
    )

st.header("Student Health Summary Report")

# =========================
# Mental Health Summary
# =========================

mental_summary = []

if st.session_state.get("sdq_completed"):

    mental_summary.append(
        f"SDQ Total Score: {st.session_state.get('sdq_total')}"
    )

    mental_summary.append(
        f"Risk Category: {st.session_state.get('sdq_category')}"
    )

# =========================
# Physical Health Summary
# =========================

physical_summary = []

if st.session_state.get("bmi_completed"):
    physical_summary.append(
        f"BMI Status: {st.session_state.get('bmi_result')}"
    )

if st.session_state.get("bp_completed"):
    physical_summary.append(
        f"Blood Pressure: {st.session_state.get('bp_result')}"
    )

if st.session_state.get("vision_completed"):
    physical_summary.append(
        f"Visual Acuity: {st.session_state.get('vision_result')}"
    )

if st.session_state.get("color_vision_completed"):
    physical_summary.append(
        f"Color Vision: {st.session_state.get('color_vision_result')}"
    )

if st.session_state.get("hair_completed"):
    physical_summary.append(
        f"Hair Health: {st.session_state.get('hair_result')}"
    )

if st.session_state.get("oral_completed"):
    physical_summary.append(
        f"Oral Health: {st.session_state.get('oral_result')}"
    )

if st.session_state.get("skin_completed"):
    physical_summary.append(
        f"Skin Health: {st.session_state.get('skin_result')}"
    )

if st.session_state.get("nail_completed"):
    physical_summary.append(
        f"Nail Health: {st.session_state.get('nail_result')}"
    )

# =========================
# Recommendations
# =========================

recommendations = []

for key in [

    "sdq_recommendation",

    "bmi_recommendation",

    "bp_recommendation",

    "vision_recommendation",

    "color_vision_recommendation",

    "hair_recommendation",

    "oral_recommendation",

    "skin_recommendation",

    "nail_recommendation"

]:

    if key in st.session_state:

        recommendations.append(
            st.session_state[key]
        )

# =========================
# Overall Recommendation
# =========================

risk_count = 0

for rec in recommendations:

    if any(

        word.lower() in rec.lower()

        for word in [

            "referral",

            "assessment",

            "professional",

            "counselling",

            "evaluation"

        ]
    ):

        risk_count += 1


if risk_count == 0:

    overall_recommendation = """
Overall screening findings are within normal limits.

Continue routine school health monitoring and healthy lifestyle practices.
"""

elif risk_count <= 2:

    overall_recommendation = """
Minor concerns identified.

Follow the recommendations provided and repeat screening during routine school health assessments.
"""

else:

    overall_recommendation = """
Multiple health concerns identified.

Comprehensive medical and/or psychological assessment is recommended.
"""

# =========================
# Display Report
# =========================

st.subheader("Mental Health Summary")

for item in mental_summary:
    st.write("•", item)

st.subheader("Physical Health Summary")

for item in physical_summary:
    st.write("•", item)

st.subheader("Recommendations")

for rec in recommendations:
    st.write("•", rec)

st.subheader("Overall Recommendation")

st.info(overall_recommendation)

# =========================
# Printable Summary
# =========================

st.subheader("Printable Summary")

report_text = f"""

STUDENT INFORMATION

Student ID: {st.session_state.get("student_id", "Not Available")}
Teacher ID: {st.session_state.get("teacher_id", "Not Available")}
Age: {st.session_state.get("age", "Not Available")}
Gender: {st.session_state.get("gender", "Not Available")}
TRAFFIC LIGHT SUMMARY

{chr(10).join(traffic_light_text)}


MENTAL HEALTH SUMMARY

{chr(10).join(mental_summary)}

PHYSICAL HEALTH SUMMARY

{chr(10).join(physical_summary)}

RECOMMENDATIONS

{chr(10).join(recommendations)}

OVERALL RECOMMENDATION

{overall_recommendation}

"""

st.download_button(

    label="Download Summary Report",

    data=report_text,

    file_name="Student_Health_Report.txt",

    mime="text/plain"

)

"""Referral Generation and Tracking:"""

# Referral Tracking


st.subheader("Referral Generation and Tracking")

referrals = []

# Mental Health

if st.session_state.get("sdq_completed"):

    if st.session_state.get("sdq_category") in [


        "High Risk"

    ]:

        referrals.append(
            "Professional counselling referral is recommended."
        )

# BMI

if st.session_state.get("bmi_completed"):

    if st.session_state.get("bmi_result") in [

        "UNDERWEIGHT",
        "OBESE"

    ]:

        referrals.append(
             "Nutritional assessment recommended. "
            "Review dietary intake and monitor growth pattern. "
            "Consider referral for medical evaluation if concerns persist."
            "Medical evaluation and weight management counselling recommended. "
            "Comprehensive assessment and follow-up are advised."
        )

# Blood Pressure

if st.session_state.get("bp_completed"):

    if st.session_state.get("bp_result") != "Normal":

        referrals.append(
            "Blood pressure exceeds age-specific screening thresholds. Repeat BP measurement and seek pediatric assessment if elevated on repeat measurement."
        )

# Visual Acuity

if st.session_state.get("vision_completed"):

    if "referral" in str(
        st.session_state.get("vision_result")
    ).lower():

        referrals.append(
            """
Visual acuity is outside normal screening limits.

Referral to an ophthalmologist or optometrist is recommended for further evaluation.
"""
        )

# Colour Vision

if st.session_state.get("color_vision_completed"):

    if "deficiency" in str(
        st.session_state.get("color_vision_result")
    ).lower():

        referrals.append(
            """"
Possible color vision deficiency detected.

Referral for formal ophthalmologic assessment is recommended.
"""
        )

# Oral Health

if st.session_state.get("oral_completed"):

    if st.session_state.get("oral_result") != "Normal":

        referrals.append(
            """
Oral health concern detected.

Dental assessment is recommended.
"""
        )

# Skin

if st.session_state.get("skin_completed"):

    if st.session_state.get("skin_result") != "Normal":

        referrals.append(
            """
Unclassified or significant abnormal skin finding.

Further clinical assessment is recommended.
"""
        )

# Hair

if st.session_state.get("hair_completed"):

    if st.session_state.get("hair_result") != "Normal":

        referrals.append(
             """
Nits/lice observed.

Regular wet combing. Over-the-counter anti-lice shampoo advised.

Abnormal finding detected.

Further clinical assessment is recommended.
"""
        )

# Nails

if st.session_state.get("nail_completed"):

    if st.session_state.get("nail_result") != "Normal":

        referrals.append(
            """
Abnormal nail findings detected.

Further clinical assessment is recommended.
Unclassified or significant nail abnormality detected.

Further clinical assessment is recommended.
"""

     )

if referrals:

    for ref in referrals:

        st.warning(ref)

else:

    st.success(
        "No additional referrals suggested based on current screening findings."
    )

"""REFERRAL STATUS"""

# =========================
# Referral Status
# =========================

st.subheader("Referral Status")

referral_status = st.selectbox(

    "Current Referral Status",

    [

        "Pending",

        "Parent Informed",

        "Appointment Scheduled",

        "Assessment Completed",

        "Closed"

    ]

)

"""REFERRAL OUTCOME"""

# =========================
# Outcome of Visit
# =========================

st.subheader("Outcome of Visit")

visit_outcome = st.selectbox(

    "Visit Outcome",

    [

        "Not Yet Available",

        "Assessment Completed",

        "Treatment Initiated",

        "No Action Required"

    ]

)

"""IMPROVEMENT OBSERVED"""

# =========================
# Improvement Tracking
# =========================

st.subheader("Improvement Observed")

improvement_status = st.selectbox(

    "Improvement Status",

    [

        "Not Reassessed",

        "Improved",

        "No Change",

        "Worsened"

    ]

)

"""FOLLOW-UP DATES"""

# =========================
# Follow-Up
# =========================

st.subheader("Follow-Up Schedule")

followup_date = st.date_input(

    "Next Follow-Up Date"

)

"""SAVE RECORD

CREATING DATAFRAME
"""

import pandas as pd
import os

st.subheader("Save Student Record")

if st.button("Save Student Record"):
  record = pd.DataFrame([{

    # =========================
    # Student Information
    # =========================

    "Student_ID":
    st.session_state.get("student_id"),

    "Teacher_ID":
    st.session_state.get("teacher_id"),

    "Assessment_Date":
    st.session_state.get("assessment_date"),

    "Age":
    st.session_state.get("age"),

    "Gender":
    st.session_state.get("gender"),

    # =========================
    # SDQ Results
    # =========================

    "Emotional":
    emotional,

    "Behavioural":
    behavioural,

    "Hyperactivity":
    hyperactivity,

    "Peer":
    peer,

    "Prosocial":
    prosocial,

    "SDQ_Total":
    st.session_state.get("sdq_total"),

    "SDQ_Category":
    st.session_state.get("sdq_category"),

    # =========================
    # Physical Health Results
    # =========================

    "BMI":
    st.session_state.get("bmi_result"),

    "Blood_Pressure":
    st.session_state.get("bp_result"),

    "Vision":
    st.session_state.get("vision_result"),

    "Color_Vision":
    st.session_state.get("color_vision_result"),

    "Hair":
    st.session_state.get("hair_result"),

    "Oral":
    st.session_state.get("oral_result"),

    "Skin":
    st.session_state.get("skin_result"),

    "Nails":
    st.session_state.get("nail_result"),

    # =========================
    # Follow-Up Tracking
    # =========================

    "Referral_Status":
    referral_status,

    "Visit_Outcome":
    visit_outcome,

    "Improvement_Status":
    improvement_status,

    "FollowUp_Date":
    followup_date

}])

file_name = "student_records.csv"

if os.path.exists(file_name):

    existing = pd.read_csv(file_name)

    record = pd.concat(
        [existing, record],
        ignore_index=True
    )

record.to_csv(
    file_name,
    index=False
)

st.success(
    "Student record saved successfully."
)

"""STUDENT DASHBOARD"""

# =========================
# Student Dashboard
# =========================

st.header("Student Dashboard")

if os.path.exists("student_records.csv"):

    dashboard_df = pd.read_csv(

        "student_records.csv"
    )

    selected_student = st.selectbox(

        "Select Student",

        dashboard_df["Student_ID"].unique()

    )

    student_df = dashboard_df[

        dashboard_df["Student_ID"]

        == selected_student

    ]

    st.dataframe(student_df)